### ISSUE TITLE
devise admin user not login in

### ISSUE THREAD

**Issue by jonybravo** [andreorvalho/foodies_cube#18]
In the new branch develop when I try to log in the output is invalid email or password.
I checked the file "20141215202737_devise_create_admin_users.rb" to be sure that the email and password were correct.

![screen shot 2015-12-02 at 07 08 13](https://cloud.githubusercontent.com/assets/8008067/11526707/853bd698-98c3-11e5-8696-72d5a4a4c148.png)

![screen shot 2015-12-02 at 07 12 21](https://cloud.githubusercontent.com/assets/8008067/11526794/215913ce-98c4-11e5-8b90-4b73218a39b8.png)

**Comment by andreorvalho** [comment]
there is a lot of things you can be doing wrong here:

1. which url are you visiting?
2. have you reset your database?(bundle exec rake db:drop db:create db:migrate)
3. you can always do bundle exec rails c
when in the console do AdminUser.first.email and check if the email is different.

otherwise solution 2 should work

**Comment by jonybravo** [comment]
the third choice did the trick.

AdminUser.create!(:email => 'admin@example.com', :password => 'password', :password_confirmation => 'password')

thanks
